Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
class Foo { int member; }

alias Alias1 = int, Alias2 = Foo; 
alias int AliasVarDeclA, AliasVarDeclB = 123; 
alias int AliasFunctionDecl(int[2] a) nothrow;

Alias1.#REFSEARCH¤【#@INTEGRAL_PROPERTIES】;
Alias2.#REFSEARCH¤【member▪#@TYPE_PROPERTIES】;


AliasVarDeclA.#REFSEARCH¤【#@INTEGRAL_PROPERTIES】;
AliasVarDeclB.#REFSEARCH¤【#@INTEGRAL_PROPERTIES】;
AliasFunctionDecl.#REFSEARCH¤【】;
