Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ TODO will be construct in future 
#PARSE(DECLARATION)   #error(SE_decl) this  #@BREAK
#STRUCTURE_EXPECTED:  InvalidSyntaxElement
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ TODO will be construct in futur
#PARSE(DECLARATION)   #error(SE_decl) this #@BREAK (  #@BREAK
#STRUCTURE_EXPECTED:  InvalidSyntaxElement
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(DECLARATION)   this(this #error(EXP_CLOSE_PARENS) #@BREAK
#STRUCTURE_EXPECTED:  DeclarationPostBlit()
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(DECLARATION)   this(this) #@FN_BODY__SIMPLE_TESTER
#STRUCTURE_EXPECTED:  DeclarationPostBlit(#@FN_BODY__SIMPLE_TESTER)
