Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(DECLARATION)   invariant #error(EXP_OPEN_PARENS)¤【()】 #@BREAK
#STRUCTURE_EXPECTED:  DeclarationInvariant()
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(DECLARATION)   invariant ( #error(EXP_CLOSE_PARENS) #@BREAK
#STRUCTURE_EXPECTED:  DeclarationInvariant()
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(DECLARATION)   invariant () #@ST_BLOCK__TESTER
#STRUCTURE_EXPECTED:  DeclarationInvariant(#@ST_BLOCK__TESTER)
