language: java

jdk:
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Prevent Travis's default of: mvn install -DskipTests=true
install:
  - mkdir -p bin-maven/dub64
  - wget http://code.dlang.org/files/dub-0.9.21-linux-x86_64.tar.gz -O - | tar -xvz -C bin-maven/dub64
  - ls -l bin-maven/dub64
  - $(pwd)/bin-maven/dub64/dub help

script: 
  - "export MAVEN_OPTS=-Xmx1024m; echo $MAVEN_OPTS; mvn clean integration-test"

