language: java

jdk:
  - oraclejdk8
#  - openjdk7

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Prevent Travis's default of: mvn install -DskipTests=true
install: ""
  - "mvn clean package"
  - "ls /home/travis/build/bruno-medeiros/DDT/bin-maven/dub"

script: mvn clean integration-test