Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
http://dlang.org/class.html#Destructor

#@SHARED_OPT《●shared》

#@SPECIAL_FN《
  ►#?STRUCTURE_EXPECTED!【~this  #error(EXP_OPEN_PARENS)¤【()】 #@BREAK● #@BREAK】●
  ►#?STRUCTURE_EXPECTED!【~this( #@CLOSEPARENS_OR_BREAK● #@CLOSEPARENS_OR_BREAK】●
  ►#?STRUCTURE_EXPECTED!【#@SHARED_OPT static this  #error(EXP_OPEN_PARENS)¤【()】 #@BREAK● #@BREAK】●
  ►#?STRUCTURE_EXPECTED!【#@SHARED_OPT static this( #@CLOSEPARENS_OR_BREAK● #@CLOSEPARENS_OR_BREAK】●
  ►#?STRUCTURE_EXPECTED!【#@SHARED_OPT static ~this  #error(EXP_OPEN_PARENS)¤【()】 #@BREAK● #@BREAK】●
  ►#?STRUCTURE_EXPECTED!【#@SHARED_OPT static ~this( #@CLOSEPARENS_OR_BREAK● #@CLOSEPARENS_OR_BREAK】●
¤》
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(DECLARATION)   #@SPECIAL_FN #@FN_BODY__SIMPLE_TESTER
#STRUCTURE_EXPECTED:  DeclarationSpecialFunction(#@SPECIAL_FN #@FN_BODY__SIMPLE_TESTER)
