Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(DECLARATION)   invariant #error(EXP_OPEN_PARENS)¤【()】 #@BREAK
#STRUCTURE_EXPECTED:  DeclarationInvariant()
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(DECLARATION)   invariant ( #error(EXP_CLOSE_PARENS) #@BREAK
#STRUCTURE_EXPECTED:  DeclarationInvariant()
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(DECLARATION)   invariant () #@BLOCK_ST
#STRUCTURE_EXPECTED:  DeclarationInvariant(#@BLOCK_ST)
