package org.eclipse.dltk.ruby.internal.ui.text;

public interface IRubySymbols extends ISymbols {
	int TokenIF = TokenUserDefined + 1;
	int TokenDO = TokenUserDefined + 2;
	int TokenIN = TokenUserDefined + 3;
	int TokenOR = TokenUserDefined + 4;
	int TokenFOR = TokenUserDefined + 5;
	int TokenAND = TokenUserDefined + 6;
	int TokenDEF = TokenUserDefined + 7;
	int TokenEND = TokenUserDefined + 8;
	int TokenNIL = TokenUserDefined + 9;
	int TokenNOT = TokenUserDefined + 10;
	int TokenCASE = TokenUserDefined + 11;
	int TokenELSE = TokenUserDefined + 12;
	int TokenWHEN = TokenUserDefined + 13;
	int TokenTHEN = TokenUserDefined + 14;
	int TokenNEXT = TokenUserDefined + 15;
	int TokenREDO = TokenUserDefined + 16;
	int TokenBREAK = TokenUserDefined + 17;
	int TokenCATCH = TokenUserDefined + 18;
	int TokenCLASS = TokenUserDefined + 19;
	int TokenWHILE = TokenUserDefined + 20;
	int TokenALIAS = TokenUserDefined + 21;
	int TokenBEGIN = TokenUserDefined + 22;
	int TokenELSIF = TokenUserDefined + 23;
	int TokenRETRY = TokenUserDefined + 24;
	int TokenUNDEF = TokenUserDefined + 25;
	int TokenUNTIL = TokenUserDefined + 26;
	int TokenYIELD = TokenUserDefined + 27;
	int TokenRETURN = TokenUserDefined + 28;
	int TokenENSURE = TokenUserDefined + 29;
	int TokenRESCUE = TokenUserDefined + 30;
	int TokenUNLESS = TokenUserDefined + 31;
	int TokenMODULE = TokenUserDefined + 32;
	int TokenRDOCBEGIN = TokenUserDefined + 33;
	int TokenRDOCEND = TokenUserDefined + 34;
	int TokenDEFINED = TokenUserDefined + 35;
}
