Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

#@AT_ATTRIB【@property●@safe●@trusted●@  system●@disable●@ #error(INVALID_ATTRIB_ID){xxx}】

#@SIMPLE_ATTRIBS_NOTM《
 ►#?STRUCTURE_EXPECTED!【#@PROT_ATTRIB{private,package,protected,public,export}● DeclarationProtection( 】●

 ►#?STRUCTURE_EXPECTED!【abstract●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【auto●DeclarationBasicAttrib( 】●
 
 ►#?STRUCTURE_EXPECTED!【deprecated●DeclarationBasicAttrib( 】●
 
 ►#?STRUCTURE_EXPECTED!【extern●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【final●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【nothrow●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【override●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【pure●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【__gshared●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【scope●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【static●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【synchronized●DeclarationBasicAttrib( 】●

 ►#?STRUCTURE_EXPECTED!【#@AT_ATTRIB●DeclarationAtAttrib(Symbol 】●
¤》

#@SIMPLE_ATTRIBS《
 ►#@SIMPLE_ATTRIBS_NOTM●
 
 ►#?STRUCTURE_EXPECTED!【const●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【immutable●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【inout●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【shared●DeclarationBasicAttrib( 】●
¤》
#@SIMPLE_ATTRIBS__SAMPLE《
 ►#?STRUCTURE_EXPECTED!【package●DeclarationProtection( 】●
 ►#?STRUCTURE_EXPECTED!【static●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【@safe●DeclarationAtAttrib(Symbol 】●
¤》

#@SIMPLE_ATTRIBS_ENUM《
 ►#?STRUCTURE_EXPECTED!【enum●DeclarationBasicAttrib( 】●
¤》
