Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂


#@STC_NOTM《
 ►#?STRUCTURE_EXPECTED!【abstract●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【auto●DeclarationBasicAttrib( 】●
 
 ►#?STRUCTURE_EXPECTED!【deprecated●DeclarationBasicAttrib( 】●
 
 ►#?STRUCTURE_EXPECTED!【extern●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【final●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【nothrow●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【override●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【pure●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【__gshared●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【scope●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【static●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【synchronized●DeclarationBasicAttrib( 】●
¤》

#@PROT_ATTRIB【#?STRUCTURE_EXPECTED!【#@《private●package●protected●public●export》● DeclarationProtection( 】】
#@AT_ATTRIB【#?STRUCTURE_EXPECTED!【#@《@property●@safe●@trusted●@  system●@disable●@ #error(INVALID_ATTRIB_ID){xxx}》●
  DeclarationAtAttrib(Symbol 】】
  
#@TYPEMOD_ATTRIB《
 ►#?STRUCTURE_EXPECTED!【const●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【immutable●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【inout●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【shared●DeclarationBasicAttrib( 】●
¤》

#@STC《
 ►#@STC_NOTM●
 ►#@TYPEMOD_ATTRIB●
¤》

#@SIMPLE_ATTRIBS_NOTM《
 ►#@STC_NOTM●
 ►#@PROT_ATTRIB●
 ►#@AT_ATTRIB●
¤》
#@SIMPLE_ATTRIBS《
 ►#@SIMPLE_ATTRIBS_NOTM●
 ►#@TYPEMOD_ATTRIB●
¤》


#@SIMPLE_ATTRIBS__SAMPLE《
 ►#?STRUCTURE_EXPECTED!【package●DeclarationProtection( 】●
 ►#?STRUCTURE_EXPECTED!【static●DeclarationBasicAttrib( 】●
 ►#?STRUCTURE_EXPECTED!【@safe●DeclarationAtAttrib(Symbol 】●
¤》

#@SIMPLE_ATTRIBS_ENUM《
 ►#?STRUCTURE_EXPECTED!【enum●DeclarationBasicAttrib( 】●
¤》
