Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

#@INTEGRAL_TYPES《byte●ubyte●short●ushort●int●uint●long●ulong●char●wchar●dchar》
#@FLOAT_TYPES《float●double●real》

▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
  void.#REFSEARCH¤【#@TYPE_PROPERTIES】;
auto _dummy = 
(void).#REFSEARCH¤【#@TYPE_PROPERTIES】;
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
  bool.#REFSEARCH¤【#@TYPE_PROPERTIES】;
auto _dummy =
(bool).#REFSEARCH¤【#@TYPE_PROPERTIES】;
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
  #@INTEGRAL_TYPES.#REFSEARCH¤【#@INTEGRAL_PROPERTIES】;
auto _dummy =
(#@INTEGRAL_TYPES).#REFSEARCH¤【#@INTEGRAL_PROPERTIES】;
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
  #@FLOAT_TYPES.#REFSEARCH¤【#@FLOAT_PROPERTIES】;
auto _dummy =
(#@FLOAT_TYPES).#REFSEARCH¤【#@FLOAT_PROPERTIES】;
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
int.init.#REFSEARCH¤【#@INTEGRAL_PROPERTIES】;
float.init.#REFSEARCH¤【#@FLOAT_PROPERTIES】;
float.stringof.#REFSEARCH¤【#@ARRAY_PROPERTIES】;

▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ primitive literals
auto _dummy = true .#REFSEARCH¤【#@TYPE_PROPERTIES】;
auto _dummy = 'a' .#REFSEARCH¤【#@INTEGRAL_PROPERTIES】;
auto _dummy = 123 .#REFSEARCH¤【#@INTEGRAL_PROPERTIES】;
auto _dummy = 123.01f .#REFSEARCH¤【#@FLOAT_PROPERTIES】;
