Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
#@SCOPE《
 ►#?STRUCTURE_EXPECTED!【 ( #@NO_ID ) ● Symbol】●
 ►#?STRUCTURE_EXPECTED!【 ( exit #@NO_ClosePARENS #@BREAK ● Symbol #@BREAK】●
 ►#?STRUCTURE_EXPECTED!【 ( exit ) ● Symbol】●
 ►#?STRUCTURE_EXPECTED!【 ( success ) ● Symbol】●
 ►#?STRUCTURE_EXPECTED!【 ( failure ) ● Symbol】●
 ►#?STRUCTURE_EXPECTED!【 ( otherId #error(INVALID_SCOPE_ID)  ) ● Symbol】●
¤》
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(STATEMENT)    scope #@SCOPE  #@ST__ANY
#STRUCTURE_EXPECTED: StatementScope( #@SCOPE  #@ST__ANY )
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(STATEMENT)    scope int foo;
#STRUCTURE_EXPECTED: DeclarationAttrib(AttribBasic DefinitionVariable(RefPrimitive DefSymbol) )
  