Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
#@PARENS_EXP《
 ►#?STRUCTURE_EXPECTED!【 #error(EXP_OPEN_PARENS)¤【】 ● MissingParenthesesExpression 】●
 ►#?STRUCTURE_EXPECTED!【 ( #@EXP_ANY__LITE #@NO_ClosePARENS #@BREAK ● #@EXP_ANY__LITE #@BREAK】●
 ►#?STRUCTURE_EXPECTED!【 ( #@EXP_ANY ) ● #@EXP_ANY 】●
¤》
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(STATEMENT)    with #@PARENS_EXP  #@ST__SAMPLE
#STRUCTURE_EXPECTED: StatementWith( #@PARENS_EXP  #@ST__SAMPLE )
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(STATEMENT)    with ( #@EXP_ANY__LITE ) #@ST__ANY
#STRUCTURE_EXPECTED: StatementWith( #@EXP_ANY__LITE #@ST__ANY )


