Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
#@PARENS_EXP《
 ►#?STRUCTURE_EXPECTED!【 ● 】●
 ►#?STRUCTURE_EXPECTED!【 ( #@EXP_ANY__LITE #@NO_ClosePARENS #@BREAK ● #@EXP_ANY__LITE #@BREAK】●
 ►#?STRUCTURE_EXPECTED!【 ( #@EXP_ANY ) ● #@EXP_ANY 】●
¤》
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(STATEMENT)    synchronized #@PARENS_EXP  #@ST__SAMPLE
#STRUCTURE_EXPECTED: StatementSynchronized( #@PARENS_EXP  #@ST__SAMPLE )
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#PARSE(STATEMENT)    synchronized ( #@EXP_ANY__LITE ) #@ST__ANY
#STRUCTURE_EXPECTED: StatementSynchronized( #@EXP_ANY__LITE #@ST__ANY )


