Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

#@__CONTEXT_START__《
 ►/*Context start*/●
 ►void _dummy() {●
 ►version(release) {●
 ►pure {●
¤》

#@__CONTEXT_END__《
 ►/*Context end*/●
 ►}●
 ►}●
 ►}●
¤》(__CONTEXT_START__)



#@SPACE_Opt《 ●》
#@SPACE_Opt2《 ●》


#@TPLPARAMS_OPT《●(TYPE, TYPE_U : TYPE[])》
#@TPLPARAMS_OPT_result《●▪TYPE▪TYPE_U》(TPLPARAMS_OPT)


#@TYPE_PROPERTIES【init▪sizeof▪alignof▪mangleof▪stringof】
#@INTEGRAL_PROPERTIES【#@TYPE_PROPERTIES▪max▪min】
#@FLOAT_PROPERTIES【#@TYPE_PROPERTIES▪infinity▪nan▪dig▪epsilon▪mant_dig▪
max_10_exp▪max_exp▪min_10_exp▪min_exp▪max▪min_normal▪re▪im▪▪】

#@ARRAY_PROPERTIES【#@TYPE_PROPERTIES▪length▪ptr▪dup▪idup▪reverse▪sort】

#@CLASS_PROPERTIES【#@TYPE_PROPERTIES▪classinfo】
