Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

#@ARCHETYPE《
  ►struct●union●class●interface●enum●
  ►function●delegate●
  ►typedef /*deprecated but still used in isexp*/●
  ►super●
  ►const●immutable●inout●shared●
  ►return●
  ►__parameters●
¤》
#@TYPE_SPEC《
  ►#?STRUCTURE_EXPECTED!【#@ARCHETYPE ● 】●
  ►#?STRUCTURE_EXPECTED!【#@TYPEREF_NE ● #@TYPEREF_NE】● 
  ►#?STRUCTURE_EXPECTED!【 #error(EXPRULE_IsTypeSpecialization) ● #@NO_TYPEREF】● 
¤》
