Ⓗ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
class Class { int member; }

auto _dummy = (new int).#REFSEARCH¤【#@INTEGRAL_PROPERTIES】;
auto _dummy = (new int[]).#REFSEARCH¤【#@ARRAY_PROPERTIES】;
auto _dummy = (new int[5]).#REFSEARCH¤【#@ARRAY_PROPERTIES】;
auto _dummy = (new Class).#REFSEARCH¤【#@TYPE_PROPERTIES▪member▪classinfo】;
auto xxx = new(; xxx.#REFSEARCH¤【】;
auto xxx2 = new; xxx2.#REFSEARCH¤【】;
